Rails.application.routes.draw do
  root 'introduction#index'
  
  get 'introduction/index'
  get 'introduction/about_us'

  get 'dashboard/edit_profile'
  get 'dashboard/manage_users'
  post 'dashboard/submit_edit_profile'
  get 'dashboard/user_profile'
  post 'dashboard/change_password'

  get 'users/signin'
  post 'users/submit_signup'
  get 'users/signup'
  post 'users/submit_signin'
  get 'users/logout'
  get 'users/confirm_account/:token', to: 'users#confirm_account'
  get 'users/forgot_password'
  get 'users/terms_and_conditions'
  get 'articles/index'
  get 'articles/show'
  get 'articles/new'
  get 'articles/edit'
  get 'articles/destroy'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/edit'
  # get 'courses/new'
  # get 'courses/delete'
end
